package seL4

/* generated with Python from a C header */

CONFIG_ARM_HIKEY_OUTSTANDING_PREFETCHERS	:: 0
CONFIG_ARM_HIKEY_PREFETCHER_STRIDE	:: 0
CONFIG_ARM_HIKEY_PREFETCHER_NPFSTRM	:: 0

CONFIG_ARCH_X86_64	:: 1

CONFIG_SEL4_ARCH	:: "x86_64"

CONFIG_ARCH_X86	:: 1
CONFIG_ARCH	:: "x86"
CONFIG_WORD_SIZE	:: 64
CONFIG_PC99_TSC_FREQUENCY	:: 0

CONFIG_PLAT_PC99	:: 1

CONFIG_PLAT	:: "pc99"

CONFIG_ARCH_X86_NEHALEM	:: 1

CONFIG_KERNEL_X86_MICRO_ARCH	:: "nehalem"
CONFIG_IRQ_IOAPIC	:: 1

CONFIG_KERNEL_IRQ_CONTROLLER	:: "IOAPIC"
CONFIG_MAX_NUM_IOAPIC	:: 1
CONFIG_XAPIC	:: 1

CONFIG_KERNEL_LAPIC_MODE	:: "XAPIC"

CONFIG_CACHE_LN_SZ	:: 64

CONFIG_IOMMU	:: 1
CONFIG_MAX_RMRR_ENTRIES	:: 32
CONFIG_MAX_VPIDS	:: 0
CONFIG_HUGE_PAGE	:: 1

CONFIG_SYSCALL	:: 1

CONFIG_KERNEL_X86_SYSCALL	:: "syscall"

CONFIG_FXSAVE	:: 1
CONFIG_KERNEL_X86_FPU	:: "FXSAVE"

CONFIG_XSAVE_FEATURE_SET	:: 0
CONFIG_XSAVE_SIZE	:: 512
CONFIG_FSGSBASE_INST	:: 1

CONFIG_KERNEL_FSGS_BASE	:: "inst"
CONFIG_MULTIBOOT_GRAPHICS_MODE_NONE	:: 1

CONFIG_KERNEL_MUTLTIBOOT_GFX_MODE	:: "none"
CONFIG_MULTIBOOT1_HEADER	:: 1
CONFIG_MULTIBOOT2_HEADER	:: 1
CONFIG_KERNEL_SKIM_WINDOW	:: 1

CONFIG_KERNEL_X86_IBRS_NONE	:: 1

CONFIG_KERNEL_X86_IBRS	:: "ibrs_none"

CONFIG_HAVE_FPU	:: 1
CONFIG_PADDR_USER_DEVICE_TOP	:: 140737488355328
CONFIG_ROOT_CNODE_SIZE_BITS	:: 12
CONFIG_TIMER_TICK_MS	:: 2
CONFIG_TIME_SLICE	:: 5
CONFIG_RETYPE_FAN_OUT_LIMIT	:: 256
CONFIG_MAX_NUM_WORK_UNITS_PER_PREEMPTION	:: 100
CONFIG_RESET_CHUNK_BITS	:: 8
CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS	:: 230
CONFIG_FASTPATH	:: 1

CONFIG_NUM_DOMAINS	:: 1
CONFIG_NUM_DOMAIN_SCHEDULES	:: 2

CONFIG_NUM_PRIORITIES	:: 256
CONFIG_MAX_NUM_NODES	:: 1

CONFIG_KERNEL_STACK_BITS	:: 12


CONFIG_PRINTING	:: 1

CONFIG_NO_BENCHMARKS	:: 1

CONFIG_KERNEL_BENCHMARK	:: "none"

CONFIG_MAX_NUM_TRACE_POINTS	:: 0
CONFIG_IRQ_REPORTING	:: 1
CONFIG_COLOUR_PRINTING	:: 1
CONFIG_USER_STACK_TRACE_LENGTH	:: 16
CONFIG_KERNEL_OPT_LEVEL_O2	:: 1

CONFIG_KERNEL_OPT_LEVEL	:: "-O2"
CONFIG_KERNEL_OPTIMISATION_CLONE_FUNCTIONS	:: 1
